[project]
authors = ["Anonymous"]
channels = ["conda-forge"]
description = "Automaton Constrained Q-Learning"
name = "acql"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.6,<3.13"
spot = ">=2.12.1,<3"

[pypi-dependencies]
acql = { path = ".", editable = true }
torch = ">=2.4.1, <3"
numpy = "<2"
scipy = ">=1.14.1, <2"
minari = { version = ">=0.5.0, <0.6", extras = ["all"] }
mlflow = ">=2.16.2, <3"
pybullet = ">=3.2.6, <4"
ipython = ">=8.28.0, <9"
ipykernel = ">=6.29.5, <7"
xmltodict = ">=0.14.1, <0.15"
tensorboard = ">=2.18.0, <3"
jax = { version = ">=0.4.34, <0.4.38", extras = ["cuda12"] }
wandb = ">=0.18.5, <0.19"
pyinstrument = ">=5.0.0, <6"
mujoco = ">=3.2.4, <4"
mujoco-mjx = ">=3.2.4, <4"
mediapy = ">=1.2.2, <2"
gym = ">=0.26.2, <0.27"
flax = ">=0.10.0, <0.11"
dm-env = ">=1.6, <2"
hydra-core = ">=1.3.2, <2"
robot-descriptions = ">=1.12.0, <2"
seaborn = ">=0.13.2, <0.14"
aim = ">=3.25.0, <4"
gymnax = ">=0.0.8, <0.0.9"
distrax = ">=0.1.5, <0.2"
evosax = ">=0.1.6, <0.2"
jupyternotify = ">=0.1.15, <0.2"
ur-rtde = ">=1.6.0, <2"
hyperopt = ">=0.2.7, <0.3"
ruff = ">=0.11.4, <0.12"
