[project]
authors = ["Tassos Manganaris <tassos.manganaris@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "task-aware-skill-composition"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.6,<4"

[pypi-dependencies]
corallab-lib = { path = "/home/tassos/phd/research/corallab-lib", extras = ["gymnasium-robotics"], editable = true }
corallab-policies = { path = "/home/tassos/phd/research/corallab-policies", editable = true }
decision-transformer = { path = "/home/tassos/phd/research/second-project/decision-transformer", editable = true }
gymnasium-robotics = { git = "https://github.com/Farama-Foundation/Gymnasium-Robotics" }
gymnasium = ">=1.0.0a2"
torch = ">=2.4.1, <3"
numpy = ">=2.1.1, <3"
scipy = ">=1.14.1, <2"
minari = { version = ">=0.5.0, <0.6", extras = ["all"] }
mlflow = ">=2.16.2, <3"
